### PR TITLE
filter aap job when monitor the AAP pod status

### PR DESCRIPTION
**Pull request by songleo**
Signed-off-by: Song Song Li <ssli@redhat.com>

### CODE REVIEW

**Comment by andreadecorte** [comment]
chris was talking about automation-job-*, I think we need to double check that -job-* is not too wide, otherwise looks ok to me

**Review by cdoan1 — APPROVED** [review]
LGTM

**Comment by cdoan1** [comment]
*-job-* is not too wide.
The check is in the aap namespace,
so either service pods are running, or the `automation-job-*` are running.

**Pull request merged**
