### PR TITLE
Pin the version for current operators

### PR DESCRIPTION
**Pull request by NemoDang**

### CODE REVIEW

**Review by songleo — APPROVED** [review]

**Comment by zkayyali812** [comment]
Test is currently failing as it is the installPlanApproval is Manual.

The CSV is not being created or approved, which is currently blocking the test from moving on.

If we'd like to set the installPlanApproval to Manual, we can potentially update the test logic to wait for and approve the installplans, rather than expecting the installPlan to automatically be approved.

**Comment by NemoDang** [comment]
Temp close this PR, after done the upgrade test.

**Pull request closed without merging**
