### PR TITLE
Add an overlay to disable alert forwarding policy for DEV testing

### PR DESCRIPTION
**Pull request by andreadecorte**

### CODE REVIEW

**Review by cdoan1 — APPROVED** [review]
LGTM

nice, you deploy a disabled policy

**Comment by songleo** [comment]
Hi @andreadecorte  I am not sure we need this dir (`dev-noalerts`) in the overlay dir. In overlay dir. we just need 3 dir:

- dev: to deploy the stack to dev env
- stage: to deploy the stack to stage env
- prod: to deploy the stack to prod env

we will delete this dir (`dev-private`) from overlay dir. if you want to test the stack on your env. I suggest you can fork the repo and use your repo to deploy&test. right? :)

@NemoDang comments? thanks
@cdoan1 FYI

**Comment by NemoDang** [comment]
Currently we use overlay as single source of truth for configuring a target management hub cluster. That means one overlay only maps to one env as we don't want to mess multiple envs's  logging data storage, alerts forwarding, etc. 

I'm working on a task to quickly deploy all the stacks with all the configs from your personal secrets, so we could do some quick validation/testing/demo in our own managed cluster first without touching the dev and stage. Will post progress asap.

**Comment by andreadecorte** [comment]
the need here was to deploy a dev without alerting, since we don't care about forwarding alerts in this environment (if we want to monitor dev alerts, then they need to be relevant) and I think this is a general need so better in the main repo, not in a fork. 
So this wasn't meant to be a full phase, but a lightweight variant dev (kind of local dev?) But I'm open to alternative solution

**Pull request merged**
