### PR TITLE
Fix image CVE issue

### PR DESCRIPTION
**Pull request by songleo**
- update the image tag to v2.4
- update doc
- update image Dockerfile to fix the CVE issue

### CODE REVIEW

**Review by NemoDang — APPROVED** [review]
lgtm

**Comment by songleo** [comment]
all images have pushed to the repo with v2.4 tag

**Review by NemoDang — APPROVED** [review]
lgtm

**Comment by songleo** [comment]
argocd image passed:

image

**Comment by songleo** [comment]
alertmanager-to-github image passed:

image

**Comment by songleo** [comment]
app-prom-config image passed:

image

**Pull request merged**
