### PR TITLE
update the cronjob version to v1

### PR DESCRIPTION
**Pull request by songleo**
Signed-off-by: Song Song Li <ssli@redhat.com>

### CODE REVIEW

**Comment by sdminonne** [comment]
I know I'm not a reviewer but I think this need to be merged :)

**Comment by songleo** [comment]
> I know I'm not a reviewer but I think this need to be merged :)

pls help to review and approve it, then we can auto-merge this pr. thanks

**Comment by songleo** [comment]
@andreadecorte added you to the owner file

**Comment by sdminonne** [comment]
lgtm

**Review by NemoDang — APPROVED** [review]
lgtm

**Pull request merged**
